# Static Defaults
replicaCount: 1
image:
  repository: virtlet.cloud/ubuntu/18.04
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 4Gi

# Names
vnf_name: test-vnf
vsn_name_0: test-vnf-vsn
int_private2_net_id: protected-net
onap_private_net_id: onap-private-net
net_attachment_definition: vfw-net-attach
# OWN Addresses
vsn_int_private2_ip_0: 192.168.20.3
vsn_onap_private_ip_0: 10.10.100.4
# Env Variables
int_private2_gw_ip: 192.168.20.1
int_private1_net_cidr: 192.168.10.0/24

# Tests
Tests:
  enabled: "yes"
  ping_count: 4
